### ISSUE TITLE
Un-escape quotes (etc) in received/sent messages

### ISSUE THREAD

**Issue by zandaarl** [lucasmetzen/foundryvtt-messenger#31]
```
20:46:04 to Mia: Oh, das ist spannend. Dass man von so etwas &quot;kleinem&quot; wirklich wach wird.
```

## Notes
- This might just mean the text is an HTML snippet and should be rendered accordingly (look into how that's done).
- Should input messages be escaped, too?
- Can Handbars' helper ("new safe string" or something like that) help with that?

**Comment by lucasmetzen** [comment]
This strangely isn't happening anymore/at the moment.
It might have been fixed by introducing AppV2 templating, or it's a peculiarity of Smaug's Foundry world.
Will test on Darksmaug's.
Closing.
